apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: <aws_account_id>.dkr.ecr.<your-region>.amazonaws.com/my-repo:latest
        ports:
        - containerPort: 5000